### ISSUE TITLE
Arguments to path.resolve must be strings

### ISSUE THREAD

**Issue by bj08** [browserquest/BrowserQuest#150]
I'm running windows 8.1 x64, and a fresh github clone. Everything apart from bCrypt installed smoothly but after some troubleshooting bCrypt installed too. However now when I do "node server/js/main.js" is gives me this error:

Warning: Native modules not compiled.  XOR performance will be degraded.
Warning: Native modules not compiled.  UTF-8 validation disabled.
[Fri Mar 07 2014 22:56:35 GMT+0000 (GMT Standard Time)] INFO Starting BrowserQue
st game server...

path.js:116
        throw new TypeError('Arguments to path.resolve must be strings');
        ^
TypeError: Arguments to path.resolve must be strings
    at Object.exports.resolve (path.js:116:15)
    at module.exports (C:\Users\Bars\Documents\new\BrowserQuest\server\js\databa
seselector.js:4:25)
    at main (C:\Users\Bars\Documents\new\BrowserQuest\server\js\main.js:45:20)
    at C:\Users\Bars\Documents\new\BrowserQuest\server\js\main.js:144:13
    at C:\Users\Bars\Documents\new\BrowserQuest\server\js\main.js:127:13
    at fs.js:266:14
    at Object.oncomplete (fs.js:107:15)

What is the problem and any solutions?

**Comment by harleyknd1** [comment]
What version of nodejs are you running? there seems to be a issue with the .10 versions as well

**Comment by ghost** [comment]
Post line 4 of databaseselector.js

**Comment by ghost** [comment]
Ignore my previous comment. Make sure you only have config.json and the other config remains as config_local.dist-json <-whatever.
