### ISSUE TITLE
Error Exporting Map [Ubuntu]

### ISSUE THREAD

**Issue by lunarcontrol** [browserquest/BrowserQuest#197]
I have been trying all day to convert my json map into the files that BrowserQuest needs. I am on Ubuntu 14.04 and it simply will not work. Here is the error that i am getting?

``
royce@royce-desktop:~/Desktop/BrowserQuest-master-2/BrowserQuest-master/tools/maps$ ./exportmap.js tiled_exported_file.json

module.js:340
    throw err;
          ^
Error: Cannot find module 'log'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/royce/Desktop/BrowserQuest-master-2/BrowserQuest-master/tools/maps/exportmap.js:4:11)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
``

**Comment by ghost** [comment]
Make sure you install dependencies and that log is installed as a module.

**Comment by lunarcontrol** [comment]
I think it worked! Did npm install log & npm install module!!

Testing it now!
