### ISSUE TITLE
Sign-in Not working

### ISSUE THREAD

**Issue by RobotsLikeKetchup** [browserquest/BrowserQuest#208]
When one signs in as a new character, you can play. However, when you try to sign in again, it doesn't allow you, by either loading infinetely or repeatedly giving the incorrect password message. This was used on google chrome.

**Comment by Veradictus** [comment]
Inspect element and paste your error here.

**Comment by fire-eggs** [comment]
```
Uncaught ReferenceError: Types is not defined
    at entityfactory.js:23
    at Function.req.execCb (require-jquery.js:1684)
    at execManager (require-jquery.js:554)
    at Object.onDep (require-jquery.js:642)
    at execManager (require-jquery.js:610)
    at Object.onDep (require-jquery.js:642)
    at execManager (require-jquery.js:610)
    at main (require-jquery.js:725)
    at callDefMain (require-jquery.js:738)
    at Object.completeLoad (require-jquery.js:1321)
```

Brave Version 1.8.95 Chromium: 81.0.4044.138 (Official Build) (64-bit)

**Comment by fire-eggs** [comment]
```
gameclient.js:62 Uncaught DOMException: Failed to construct 'WebSocket': An insecure WebSocket connection may not be initiated from a page loaded over HTTPS.
    at Class.connect (https://browserquest.herokuapp.com/js/gameclient.js:62:35)
    at Class.connect (https://browserquest.herokuapp.com/js/game.js:759:29)
    at https://browserquest.herokuapp.com/js/game.js:698:26
connect @ gameclient.js:62
connect @ game.js:759
(anonymous) @ game.js:698
```

**Comment by slanger** [comment]
> ```
> gameclient.js:62 Uncaught DOMException: Failed to construct 'WebSocket': An insecure WebSocket connection may not be initiated from a page loaded over HTTPS.
>     at Class.connect (https://browserquest.herokuapp.com/js/gameclient.js:62:35)
>     at Class.connect (https://browserquest.herokuapp.com/js/game.js:759:29)
>     at https://browserquest.herokuapp.com/js/game.js:698:26
> connect @ gameclient.js:62
> connect @ game.js:759
> (anonymous) @ game.js:698
> ```

I got this same error when submitting a new character, and it just says "loading" forever. As a work-around, you can replace "https://" with "http://" in the URL. Of course, this is not ideal though, as HTTP is not as secure as HTTPS.

**Comment by CertifiedWebMaster** [comment]
Uh oh

 

    On Sunday, February 14, 2021, 11:09:31 PM EST, Mark Langer <notifications@github.com> wrote:  
 
 


gameclient.js:62 Uncaught DOMException: Failed to construct 'WebSocket': An insecure WebSocket connection may not be initiated from a page loaded over HTTPS.
    at Class.connect (https://browserquest.herokuapp.com/js/gameclient.js:62:35)
    at Class.connect (https://browserquest.herokuapp.com/js/game.js:759:29)
    at https://browserquest.herokuapp.com/js/game.js:698:26
connect @ gameclient.js:62
connect @ game.js:759
(anonymous) @ game.js:698


I got this same error when submitting a new character, and it just says "loading" forever. As a work-around, you can replace "https://" with "http://" in the URL. Of course, this is not ideal though, as HTTP is not as secure as HTTPS.
