### ISSUE TITLE
Stuck loading, creating new character.  Love this game, please fix  :)

### ISSUE THREAD

**Issue by ztoddw** [browserquest/BrowserQuest#217]
On https://browserquest.herokuapp.com/ it stays stuck on the Loading page after trying to create a new character.

Errors:

```
index.js:1810          GET https://browserquest.herokuapp.com/img/spritesheet.png 404 (Not Found)
getOKResponse @ index.js:1810
loadAsDataURL @ index.js:1837
getImageDataURL @ index.js:1919
(anonymous) @ index.js:1894
getImageDetails @ index.js:1888
(anonymous) @ index.js:2603
(anonymous) @ index.js:2703
(anonymous) @ index.js:2703
(anonymous) @ index.js:4242
(anonymous) @ index.js:4239
modifySheet @ index.js:4120
buildOverrides @ index.js:4634
render @ index.js:4647
(anonymous) @ index.js:5634
createDynamicStyleOverrides @ index.js:5633
runDynamicStyle @ index.js:5762
createThemeAndWatchForUpdates @ index.js:5768
createOrUpdateDynamicTheme @ index.js:5916
onMessage @ index.js:6123

index.js:1810          GET https://browserquest.herokuapp.com/img/common/gplus.png 404 (Not Found)
getOKResponse @ index.js:1810
loadAsDataURL @ index.js:1837
getImageDataURL @ index.js:1919
(anonymous) @ index.js:1894
getImageDetails @ index.js:1888
(anonymous) @ index.js:2603
(anonymous) @ index.js:2703
(anonymous) @ index.js:2703
(anonymous) @ index.js:4242
(anonymous) @ index.js:4239
modifySheet @ index.js:4120
buildOverrides @ index.js:4634
render @ index.js:4647
(anonymous) @ index.js:5634
createDynamicStyleOverrides @ index.js:5633
runDynamicStyle @ index.js:5762
createThemeAndWatchForUpdates @ index.js:5768
createOrUpdateDynamicTheme @ index.js:5916
onMessage @ index.js:6123

log.js:29 Error getting image data for sprite : firefox
Logger.error @ log.js:29
createHurtSprite @ sprite.js:86
(anonymous) @ game.js:171
(anonymous) @ gametypes.js:395
Types.forEachKind @ gametypes.js:372
Types.forEachArmorKind @ gametypes.js:393
initHurtSprites @ game.js:170
setSpriteScale @ game.js:358
run @ game.js:666
startGame @ app.js:134
tryStartingGame @ app.js:96
(anonymous) @ main.js:543
handle @ require-jquery.js:5014
eventHandle @ require-jquery.js:4648

log.js:29 Error getting image data for sprite : clotharmor
Logger.error @ log.js:29
createHurtSprite @ sprite.js:86
(anonymous) @ game.js:171
(anonymous) @ gametypes.js:395
Types.forEachKind @ gametypes.js:372
Types.forEachArmorKind @ gametypes.js:393
initHurtSprites @ game.js:170
setSpriteScale @ game.js:358
run @ game.js:666
startGame @ app.js:134
tryStartingGame @ app.js:96
(anonymous) @ main.js:543
handle @ require-jquery.js:5014
eventHandle @ require-jquery.js:4648

log.js:29 Error getting image data for sprite : leatherarmor
Logger.error @ log.js:29
createHurtSprite @ sprite.js:86
(anonymous) @ game.js:171
(anonymous) @ gametypes.js:395
Types.forEachKind @ gametypes.js:372
Types.forEachArmorKind @ gametypes.js:393
initHurtSprites @ game.js:170
setSpriteScale @ game.js:358
run @ game.js:666
startGame @ app.js:134
tryStartingGame @ app.js:96
(anonymous) @ main.js:543
handle @ require-jquery.js:5014
eventHandle @ require-jquery.js:4648

log.js:29 Error getting image data for sprite : mailarmor
Logger.error @ log.js:29
createHurtSprite @ sprite.js:86
(anonymous) @ game.js:171
(anonymous) @ gametypes.js:395
Types.forEachKind @ gametypes.js:372
Types.forEachArmorKind @ gametypes.js:393
initHurtSprites @ game.js:170
setSpriteScale @ game.js:358
run @ game.js:666
startGame @ app.js:134
tryStartingGame @ app.js:96
(anonymous) @ main.js:543
handle @ require-jquery.js:5014
eventHandle @ require-jquery.js:4648

log.js:29 Error getting image data for sprite : platearmor
Logger.error @ log.js:29
createHurtSprite @ sprite.js:86
(anonymous) @ game.js:171
(anonymous) @ gametypes.js:395
Types.forEachKind @ gametypes.js:372
Types.forEachArmorKind @ gametypes.js:393
initHurtSprites @ game.js:170
setSpriteScale @ game.js:358
run @ game.js:666
startGame @ app.js:134
tryStartingGame @ app.js:96
(anonymous) @ main.js:543
handle @ require-jquery.js:5014
eventHandle @ require-jquery.js:4648

log.js:29 Error getting image data for sprite : redarmor
Logger.error @ log.js:29
createHurtSprite @ sprite.js:86
(anonymous) @ game.js:171
(anonymous) @ gametypes.js:395
Types.forEachKind @ gametypes.js:372
Types.forEachArmorKind @ gametypes.js:393
initHurtSprites @ game.js:170
setSpriteScale @ game.js:358
run @ game.js:666
startGame @ app.js:134
tryStartingGame @ app.js:96
(anonymous) @ main.js:543
handle @ require-jquery.js:5014
eventHandle @ require-jquery.js:4648

log.js:29 Error getting image data for sprite : goldenarmor
Logger.error @ log.js:29
createHurtSprite @ sprite.js:86
(anonymous) @ game.js:171
(anonymous) @ gametypes.js:395
Types.forEachKind @ gametypes.js:372
Types.forEachArmorKind @ gametypes.js:393
initHurtSprites @ game.js:170
setSpriteScale @ game.js:358
run @ game.js:666
startGame @ app.js:134
tryStartingGame @ app.js:96
(anonymous) @ main.js:543
handle @ require-jquery.js:5014
eventHandle @ require-jquery.js:4648

Mixed Content: The page at '<URL>' was loaded over HTTPS, but attempted to connect to the insecure WebSocket endpoint 'ws://browserquest.herokuapp.com/'. This request has been blocked; this endpoint must be available over WSS.
Mixed Content: The page at '<URL>' was loaded over HTTPS, but attempted to connect to the insecure WebSocket endpoint 'ws://browserquest.herokuapp.com/'. This request has been blocked; this endpoint must be available over WSS.
Mixed Content: The page at '<URL>' was loaded over HTTPS, but attempted to connect to the insecure WebSocket endpoint 'ws://browserquest.herokuapp.com/'. This request has been blocked; this endpoint must be available over WSS.
Mixed Content: The page at '<URL>' was loaded over HTTPS, but attempted to connect to the insecure WebSocket endpoint 'ws://browserquest.herokuapp.com/'. This request has been blocked; this endpoint must be available over WSS.
Mixed Content: The page at '<URL>' was loaded over HTTPS, but attempted to connect to the insecure WebSocket endpoint 'ws://browserquest.herokuapp.com/'. This request has been blocked; this endpoint must be available over WSS.
Mixed Content: The page at '<URL>' was loaded over HTTPS, but attempted to connect to the insecure WebSocket endpoint 'ws://browserquest.herokuapp.com/'. This request has been blocked; this endpoint must be available over WSS.
Mixed Content: The page at '<URL>' was loaded over HTTPS, but attempted to connect to the insecure WebSocket endpoint 'ws://browserquest.herokuapp.com/'. This request has been blocked; this endpoint must be available over WSS.
Mixed Content: The page at '<URL>' was loaded over HTTPS, but attempted to connect to the insecure WebSocket endpoint 'ws://browserquest.herokuapp.com/'. This request has been blocked; this endpoint must be available over WSS.

gameclient.js:62 Uncaught DOMException: Failed to construct 'WebSocket': An insecure WebSocket connection may not be initiated from a page loaded over HTTPS.
    at Class.connect (https://browserquest.herokuapp.com/js/gameclient.js:62:35)
    at Class.connect (https://browserquest.herokuapp.com/js/game.js:759:29)
    at https://browserquest.herokuapp.com/js/game.js:698:26
connect @ gameclient.js:62
connect @ game.js:759
(anonymous) @ game.js:698
setInterval (async)
run @ game.js:668
startGame @ app.js:134
tryStartingGame @ app.js:96
(anonymous) @ main.js:543
handle @ require-jquery.js:5014
eventHandle @ require-jquery.js:4648

gameclient.js:62 Uncaught DOMException: Failed to construct 'WebSocket': An insecure WebSocket connection may not be initiated from a page loaded over HTTPS.
    at Class.connect (https://browserquest.herokuapp.com/js/gameclient.js:62:35)
    at Class.connect (https://browserquest.herokuapp.com/js/game.js:759:29)
    at https://browserquest.herokuapp.com/js/game.js:698:26
connect @ gameclient.js:62
connect @ game.js:759
(anonymous) @ game.js:698
setInterval (async)
run @ game.js:668
startGame @ app.js:134
tryStartingGame @ app.js:96
(anonymous) @ main.js:543
handle @ require-jquery.js:5014
eventHandle @ require-jquery.js:4648

gameclient.js:62 Uncaught DOMException: Failed to construct 'WebSocket': An insecure WebSocket connection may not be initiated from a page loaded over HTTPS.
    at Class.connect (https://browserquest.herokuapp.com/js/gameclient.js:62:35)
    at Class.connect (https://browserquest.herokuapp.com/js/game.js:759:29)
    at https://browserquest.herokuapp.com/js/game.js:698:26
connect @ gameclient.js:62
connect @ game.js:759
(anonymous) @ game.js:698
setInterval (async)
run @ game.js:668
startGame @ app.js:134
tryStartingGame @ app.js:96
(anonymous) @ main.js:543
handle @ require-jquery.js:5014
eventHandle @ require-jquery.js:4648

gameclient.js:62 Uncaught DOMException: Failed to construct 'WebSocket': An insecure WebSocket connection may not be initiated from a page loaded over HTTPS.
    at Class.connect (https://browserquest.herokuapp.com/js/gameclient.js:62:35)
    at Class.connect (https://browserquest.herokuapp.com/js/game.js:759:29)
    at https://browserquest.herokuapp.com/js/game.js:698:26
connect @ gameclient.js:62
connect @ game.js:759
(anonymous) @ game.js:698
setInterval (async)
run @ game.js:668
startGame @ app.js:134
tryStartingGame @ app.js:96
(anonymous) @ main.js:543
handle @ require-jquery.js:5014
eventHandle @ require-jquery.js:4648

gameclient.js:62 Uncaught DOMException: Failed to construct 'WebSocket': An insecure WebSocket connection may not be initiated from a page loaded over HTTPS.
    at Class.connect (https://browserquest.herokuapp.com/js/gameclient.js:62:35)
    at Class.connect (https://browserquest.herokuapp.com/js/game.js:759:29)
    at https://browserquest.herokuapp.com/js/game.js:698:26
connect @ gameclient.js:62
connect @ game.js:759
(anonymous) @ game.js:698
setInterval (async)
run @ game.js:668
startGame @ app.js:134
tryStartingGame @ app.js:96
(anonymous) @ main.js:543
handle @ require-jquery.js:5014
eventHandle @ require-jquery.js:4648

gameclient.js:62 Uncaught DOMException: Failed to construct 'WebSocket': An insecure WebSocket connection may not be initiated from a page loaded over HTTPS.
    at Class.connect (https://browserquest.herokuapp.com/js/gameclient.js:62:35)
    at Class.connect (https://browserquest.herokuapp.com/js/game.js:759:29)
    at https://browserquest.herokuapp.com/js/game.js:698:26
connect @ gameclient.js:62
connect @ game.js:759
(anonymous) @ game.js:698
setInterval (async)
run @ game.js:668
startGame @ app.js:134
tryStartingGame @ app.js:96
(anonymous) @ main.js:543
handle @ require-jquery.js:5014
eventHandle @ require-jquery.js:4648

gameclient.js:62 Uncaught DOMException: Failed to construct 'WebSocket': An insecure WebSocket connection may not be initiated from a page loaded over HTTPS.
    at Class.connect (https://browserquest.herokuapp.com/js/gameclient.js:62:35)
    at Class.connect (https://browserquest.herokuapp.com/js/game.js:759:29)
    at https://browserquest.herokuapp.com/js/game.js:698:26
connect @ gameclient.js:62
connect @ game.js:759
(anonymous) @ game.js:698
setInterval (async)
run @ game.js:668
startGame @ app.js:134
tryStartingGame @ app.js:96
(anonymous) @ main.js:543
handle @ require-jquery.js:5014
eventHandle @ require-jquery.js:4648

gameclient.js:62 Uncaught DOMException: Failed to construct 'WebSocket': An insecure WebSocket connection may not be initiated from a page loaded over HTTPS.
    at Class.connect (https://browserquest.herokuapp.com/js/gameclient.js:62:35)
    at Class.connect (https://browserquest.herokuapp.com/js/game.js:759:29)
    at https://browserquest.herokuapp.com/js/game.js:698:26
connect @ gameclient.js:62
connect @ game.js:759
(anonymous) @ game.js:698
setInterval (async)
run @ game.js:668
startGame @ app.js:134
tryStartingGame @ app.js:96
(anonymous) @ main.js:543
handle @ require-jquery.js:5014
eventHandle @ require-jquery.js:4648

```

**Comment by Veradictus** [comment]
This project is long abandoned.
